version: '3.8'

services:
  # 1. База данных PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: mtg_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    restart: always

  # 2. Брокер Redis
  redis:
    image: redis:7-alpine
    container_name: mtg_redis
    restart: always

  # 3. Приложение Django (Gunicorn)
  app:
    build: .
    container_name: mtg_app
    command: gunicorn mtg_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    expose:
      - 8000
    depends_on:
      - db
      - redis
    env_file:
      - .env.prod # Файл с секретными настройками
    restart: always

  # 4. Celery Worker (Работник)
  celery:
    build: .
    container_name: mtg_celery_worker
    command: celery -A mtg_project worker --loglevel=info
    depends_on:
      - app
      - db
      - redis
    env_file:
      - .env.prod
    restart: always

  # 5. Celery Beat (Будильник)
  celery-beat:
    build: .
    container_name: mtg_celery_beat
    command: celery -A mtg_project beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - app
      - db
      - redis
    env_file:
      - .env.prod
    restart: always

  # 6. Nginx (Фронт-сервер)
  nginx:
    image: nginx:latest
    container_name: mtg_nginx
    ports:
      - "80:80" # 80-й порт сервера -> 80-й порт контейнера
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Наш конфиг
      - ./media:/app/media # Доступ к картинкам
      - ./staticfiles:/app/staticfiles # Доступ к CSS/JS
    depends_on:
      - app
    restart: always

volumes:
  postgres_data: